apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalogs" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: catalogs
data:
{{- range $catalogName, $catalogProperties := .Values.catalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}
---
