apiVersion: v1
kind: Service
metadata:
  name: {{ template "metastore.fullname" . }}
  labels:
    app: {{ template "metastore.name" . }}
    chart: {{ template "metastore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: metastore
spec:
  selector:
    app: {{ template "metastore.name" . }}
    release: {{ .Release.Name }}
    component: metastore
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9083
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
{{ else }}
  type: ClusterIP
{{ end }}
